### ISSUE TITLE
Replace train emoji with boat to maintain nautical theme

### ISSUE THREAD

**Issue by scottveirs** [orcasound/.github#3]
Take it or leave it, @hgordon6634 : 

Thought the `ferry` or `passenger_ship` emojis might be fun to try -- 
 
<img width="1082" alt="Screen Shot 2021-11-09 at 1 28 32 PM" src="https://user-images.githubusercontent.com/14044595/141008353-48831f9d-610f-4a7b-9930-12405640f234.png">

**Comment by hgordon6634** [comment]
Sure! The emojis look a little different in Github, so I'll go ahead and change it to the passenger ship emoji 🛳️ since the ferry emoji ⛴️ is a little hard to tell what it is.

**Comment by hgordon6634** [comment]
Change committed to master branch
