### ISSUE TITLE
Add Slack invite?

### ISSUE THREAD

**Issue by scottveirs** [orcasound/.github#4]
The text mentions and links to specific Slack channels, but there is no invitation. I'm not sure how that will work for incoming folks who aren't yet members of the Orcasound Slack, or -- even worse -- don't have Slack accounts yet.

One solution could be to offer a standing invite to the Orcasound Slack (above the fold maybe at the first mention of Slack?). We do so on the DemocracyLab project page and so far the incoming people have been high-quality and well-behaved (only one spammer in ~2 years.)

The current invite link is [https://join.slack.com/t/orcasound/shared_invite/zt-bd1jk2q9-FjeWr3OzocDBwDgS0g1FdQ](https://join.slack.com/t/orcasound/shared_invite/zt-bd1jk2q9-FjeWr3OzocDBwDgS0g1FdQ)

**Comment by hgordon6634** [comment]
I'm not 100% sure how Slack works, but when I was joining as a mentor to a hackathon that was completely slack-based, they just had links like I used on their website and it took you straight to their Slack. I think it prompts you to make a slack account or link your google account if you don't have a slack account? But I could be totally wrong! I will double check when I get a moment.

**Comment by scottveirs** [comment]
In my experience on-boarding someone new to Slack can be a bit of a nightmare, @hgordon6634 ... Some folks don't have the mobile app or desktop client installed and that can cause hiccups. Others have one workspace but then run into issues adding Orcasound as an additional workspace on either the desktop client, or the mobile app...

I'll try clicking on the Slack channel links from a different device (my son's computer!) and report back.

**Comment by scottveirs** [comment]
The "Copy link" option upon generating a new invitation from within the Slack web app (see screenshots for UI as of today) seems to be mostly working for folks, so I'll resolve this issue for now.

<img width="319" alt="Screen Shot 2022-11-17 at 11 59 57 AM" src="https://user-images.githubusercontent.com/14044595/202547176-1e64411a-0d43-4a2a-9296-3803ea318281.png">

<img width="704" alt="Screen Shot 2022-11-17 at 12 00 10 PM" src="https://user-images.githubusercontent.com/14044595/202547173-eadbbb71-a64b-4823-b8a9-c9bc3b0a3f6c.png">

<img width="701" alt="Screen Shot 2022-11-17 at 12 00 20 PM" src="https://user-images.githubusercontent.com/14044595/202547160-3c3bec38-3194-474e-9f4b-da5580414b5d.png">

<img width="689" alt="Screen Shot 2022-11-17 at 11 59 44 AM" src="https://user-images.githubusercontent.com/14044595/202547179-bfc3fc82-49ce-4e3c-a25b-dfdbc5c896a4.png">

<img width="710" alt="Screen Shot 2022-11-17 at 11 59 35 AM" src="https://user-images.githubusercontent.com/14044595/202547391-81a7c7ed-28b6-48ca-9633-749b100c3d68.png">
