### ISSUE TITLE
Slack link Problem on GSoC Community Page!

### ISSUE THREAD

**Issue by sahilempire** [orcasound/.github#8]
### Discussed in https://github.com/orgs/orcasound/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **sahilempire** November 17, 2022</sup>
The link given on the Community Page of GSoC `https://summerofcode.withgoogle.com/programs/2022/organizations/orcasound` is not working correctly, as I want to work with your Organisation, And I want to discuss something with the maintainers, but because of the link error, I can't do that.

</div>

**Comment by scottveirs** [comment]
Thanks for flagging, @sahilempire ! That may have happened because Slack now says invite links must expire and are limited to 400 recipients... which is new info I see when I try to generate an invite link.

In any case, I've updated the link (and was still able to set it to not expire), so let me know if that doesn't resolve the issue for you.

**Comment by sahilempire** [comment]
Still, that link shows the following error when I'm signing in:

> yoursahilgupta@gmail.com doesn’t have an account on this workspace.

**Comment by sahilempire** [comment]
As I like the motive and technology in your organization and I want to work with orcasound, but I don't know where to begin, so can you help me through? @scottveirs

**Comment by scottveirs** [comment]
@sahilempire you can study our Github repos and read through the onboarding info at [github.com/orcasound], but usually the first step is to get you engaged within Slack, so can you try this direct invitation link?

[https://join.slack.com/t/orcasound/shared_invite/zt-1jr7te193-ObLYcTxx4s7SO7EA9kmcaw](https://join.slack.com/t/orcasound/shared_invite/zt-1jr7te193-ObLYcTxx4s7SO7EA9kmcaw)

And if it still doesn't work, can you send a screenshot of the error you get, plus info on what device/OS and implementation of Slack you are using to process the invitation (i.e. web app, desktop, mobile app)?

**Comment by sahilempire** [comment]
It's working now, thank you.
